import AppProvider from "@/configs/AppProvider";
import theme from "@/styles/theme";
import { ThemeProvider, CssBaseline } from '@mui/material';
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { Source_Sans_3, STIX_Two_Text } from "next/font/google";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const sourceSans3 = Source_Sans_3({
  variable: "--font-source-sans-3",
  subsets: ["vietnamese"],
});
const stixTwoText = STIX_Two_Text({
  variable: "--font-stix-two-text",
  subsets: ["vietnamese"],
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Quản lí trường mầm non",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {


  // const cookieStore = cookies();
  // const token = (await cookieStore).get("token");
  // console.log(token);

  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/favicon.svg' sizes='any' />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sourceSans3.variable} ${stixTwoText.variable} antialiased`}
      >
        <AppProvider>

          <ThemeProvider theme={theme}>
            <CssBaseline />
            {children}
          </ThemeProvider>

          <ToastContainer
            position='top-right'
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme='light'
          />
        </AppProvider>
      </body>
    </html>
  );
}
// function replace(arg0: string) {
//   throw new Error("Function not implemented.");
// }

